In [1]:
import pandas as pd

df = pd.read_excel('assets/bpdprielist.xlsx')

In [2]:
df.head()

                                      Code                    Name Packing
0  Company :ABBOT LABORATORIES (I) LTD PED                     NaN     NaN
1                                     6892          ENSURE  GOLD *   400GM
2                                     3747            ENSURE BIG *  1000GM
3                                      286     ENSURE CHOCOLATE  *   400GM
4                                   751550  ENSURE CHOCOLATE 200GM   200GM

In [3]:
splits=[]

In [4]:
for ind in df.index: 
    if(pd.isna(df['Name'][ind])):
        splits.append(ind)

In [5]:
splits

[0,
 44,
 80,
 109,
 146,
 162,
 196,
 235,
 263,
 271,
 299,
 350,
 383,
 422,
 452,
 469,
 531,
 552,
 581,
 634,
 681,
 719,
 738,
 779,
 803,
 816,
 878,
 950,
 959,
 1004,
 1056,
 1082,
 1127,
 1157,
 1171,
 1193,
 1207,
 1249,
 1258,
 1262,
 1267,
 1274,
 1374,
 1383,
 1418,
 1483,
 1508,
 1526,
 1566,
 1595,
 1603,
 1627,
 1642,
 1670,
 1695,
 1774,
 1852,
 1920,
 1947,
 1977,
 2028,
 2078,
 2122,
 2135,
 2151,
 2281,
 2284,
 2286,
 2317,
 2334,
 2358,
 2383,
 2394,
 2400,
 2781,
 2818,
 2823,
 2850,
 2865,
 2893,
 2925,
 2937,
 2942,
 2949,
 2966,
 2974,
 2981,
 3039,
 3110,
 3145,
 3194,
 3207,
 3226,
 3261,
 3276,
 3326,
 3341,
 3354,
 3407,
 3438,
 3470,
 3504,
 3535,
 3560,
 3585,
 3617,
 3636,
 3663,
 3680,
 3685,
 3712,
 3730,
 3768,
 3770,
 3783,
 3800,
 3852,
 3889,
 3940,
 3962,
 3972,
 3983,
 3995,
 3997,
 4008,
 4023,
 4051,
 4053,
 4078,
 4099,
 4114,
 4149,
 4177,
 4179,
 4181,
 4188,
 4201,
 4222,
 4226,
 4229,
 4250,
 4289,
 4298,
 4335,
 4376,
 4385,
 4402,
 4408,
 4433,
 4443,
 4484,
 4496,
 4501,
 4612,
 4626,
 4678,
 4718,
 4745,
 4782,
 4821,
 4885,
 4904,
 4921,
 4967,
 5011,
 5062,
 5079,
 5123,
 5144,
 5153,
 5160,
 5174,
 5285,
 5313,
 5343,
 5354,
 5402,
 5436,
 5477,
 5507,
 5546,
 5572,
 5629,
 5656,
 5720,
 5734,
 5759,
 5788,
 5790,
 5814,
 5844,
 5936,
 5949,
 5989,
 5991,
 6077,
 6171,
 6176,
 6199,
 6243,
 6345,
 6375,
 6378,
 6428,
 6511,
 6582,
 6604,
 6657,
 6698,
 6798,
 6853,
 6881,
 6916,
 6944,
 6977,
 7029,
 7086,
 7136,
 7156,
 7203,
 7258,
 7277,
 7307,
 7391,
 7411,
 7443,
 7476,
 7501,
 7506,
 7529,
 7537,
 7546,
 7563,
 7569,
 7573,
 7609,
 7629]

In [6]:
dfs=[]

In [7]:
for i in range(len(splits) -1):
    current_df = df[splits[i]:splits[i+1]]
    current_df.reset_index(drop=True, inplace=True)
    dfs.append(current_df)

In [103]:
for ind in dfs[0].index:
    if(ind == 0):
        print(getCompanyName(df["Code"][ind]))

ABBOT LABORATORIES (I) LTD PED

In [8]:
def getCompanyName(name:str):
    return name.split(':')[-1]

In [11]:
def getCompanyFromDf(adf:pd.core.frame.DataFrame):
    for ind in adf.index:
        if(ind == 0):
            return getCompanyName(adf["Code"][ind])

In [12]:
for adf in dfs:
    print(getCompanyFromDf(adf))
    adf = adf[1:]

Code       Company :ABBOT LABORATORIES (I) LTD PED
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOT LABORATORIES (I) LTD PED
Code       Company :ABBOTT CARDIAC
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOTT CARDIAC
Code       Company :ABBOTT INDIA GEN NEXT
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOTT INDIA GEN NEXT
Code       Company :ABBOTT INDIA LIMITED
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOTT INDIA LIMITED
Code       Company :ABBOTT INDIA OTC LTD
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOTT INDIA OTC LTD
Code       Company :ABBOTT LENBROOK
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOTT LENBROOK
Code       Company :ABBOTT MAGNUS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOTT MAGNUS
Code       Company :ABBOTT SOLVAY PHARMA INDIA LIM
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ABBOTT SOLVAY PHARMA INDIA LIM
Code       Company :ALEMBIC ALCARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALEMBIC ALCARE
Code       Company :ALEMBIC CORAZON
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALEMBIC CORAZON
Code       Company :ALEMBIC LTD
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALEMBIC LTD
Code       Company :ALEMBIC ZENOVI
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALEMBIC ZENOVI
Code       Company :ALKEM
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM
Code       Company :ALKEM ACE AURA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM ACE AURA
Code       Company :ALKEM ALPHA MAX
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM ALPHA MAX
Code       Company :ALKEM ARISE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM ARISE
Code       Company :ALKEM BERGEN ASTA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM BERGEN ASTA
Code       Company :ALKEM BERGEN NOVA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM BERGEN NOVA
Code       Company :ALKEM CARDIOLOGY
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM CARDIOLOGY
Code       Company :ALKEM DIABETOLOGY
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM DIABETOLOGY
Code       Company :ALKEM HOSPICARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM HOSPICARE
Code       Company :ALKEM IMPERIA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM IMPERIA
Code       Company :ALKEM MAIN ALTIS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM MAIN ALTIS
Code       Company :ALKEM METABOLICS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM METABOLICS
Code       Company :ALKEM NEW
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM NEW
Code       Company :ALKEM PENTACARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM PENTACARE
Code       Company :ALKEM PRIZMA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALKEM PRIZMA
Code       Company :ALLMBIC ELENA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ALLMBIC ELENA
Code       Company :ATLINA LIFE SCIENCES
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ATLINA LIFE SCIENCES
Code       Company :AVENTIS CARDIAC
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
AVENTIS CARDIAC
Code       Company :AVENTIS CNS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
AVENTIS CNS
Code       Company :AVENTIS DIABETO
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
AVENTIS DIABETO
Code       Company :AVENTIS INTERNAL MEDICINE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
AVENTIS INTERNAL MEDICINE
Code       Company :AVENTIS ONSITE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
AVENTIS ONSITE
Code       Company :AVENTIS UNIVERSAL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
AVENTIS UNIVERSAL
Code       Company :AVENTIS-ACUTE CARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
AVENTIS-ACUTE CARE
Code       Company :BE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
BE
Code       Company :BOOTS PIRAMAL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
BOOTS PIRAMAL
Code       Company :CELAGENEX RESEARCH INDIA PVT L
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CELAGENEX RESEARCH INDIA PVT L
Code       Company :CENTRA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CENTRA
Code       Company :CIPLA  IMPULSE 1
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA  IMPULSE 1
Code       Company :CIPLA CREST
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA CREST
Code       Company :CIPLA ENT
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA ENT
Code       Company :CIPLA FORESIGHT
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA FORESIGHT
Code       Company :CIPLA INSPIRA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA INSPIRA
Code       Company :CIPLA LIFE CARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA LIFE CARE
Code       Company :CIPLA LTD NURTURE 2
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA LTD NURTURE 2
Code       Company :CIPLA NURTURE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA NURTURE
Code       Company :CIPLA OPTIMUS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA OPTIMUS
Code       Company :CIPLA PROTEC
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA PROTEC
Code       Company :CIPLA QUADRA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA QUADRA
Code       Company :CIPLA RESP AR AND PH CARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA RESP AR AND PH CARE
Code       Company :CIPLA RESPICARE -2
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA RESPICARE -2
Code       Company :CIPLA RESPIRATORY-1
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA RESPIRATORY-1
Code       Company :CIPLA RESPITORY  MISC
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA RESPITORY  MISC
Code       Company :CIPLA SPECIALITY
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA SPECIALITY
Code       Company :CIPLA SUPRACARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA SUPRACARE
Code       Company :CIPLA URO 1
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA URO 1
Code       Company :CIPLA VITALIS 3
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA VITALIS 3
Code       Company :CIPLA VITALIS CRITICAL CARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA VITALIS CRITICAL CARE
Code       Company :CIPLA VITALIS-1
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA VITALIS-1
Code       Company :CIPLA VITALIS-2
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA VITALIS-2
Code       Company :CIPLA XTERNA 1
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA XTERNA 1
Code       Company :CIPLA XTERNA 2
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA XTERNA 2
Code       Company :CIPLA ZESTA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
CIPLA ZESTA
Code       Company :COSMOCARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
COSMOCARE
Code       Company :DARA PHARMACEUTICALS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
DARA PHARMACEUTICALS
Code       Company :DR.REDDYS LABORATORIES LIMITED
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
DR.REDDYS LABORATORIES LIMITED
Code       Company :ELDAR TORRENT SPIRITUS TEAM A
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ELDAR TORRENT SPIRITUS TEAM A
Code       Company :ELDAR TORRENT TEAM B
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ELDAR TORRENT TEAM B
Code       Company :EMCURE PHARAMACEUTICALS LTD,
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
EMCURE PHARAMACEUTICALS LTD,
Code       Company :EMCURE VERTEX
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
EMCURE VERTEX
Code       Company :ENCURE INFIUS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
ENCURE INFIUS
Code       Company :GENERAL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GENERAL
Code       Company :GLARIZONTO PHARMA PVT LTD
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLARIZONTO PHARMA PVT LTD
Code       Company :GLAXO INDIA TEAM-3
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLAXO INDIA TEAM-3
Code       Company :GLAXO SHEFEL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLAXO SHEFEL
Code       Company :GLAXO SMITHKLINE PHARMA LTD
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLAXO SMITHKLINE PHARMA LTD
Code       Company :GLAXO TEAM-8
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLAXO TEAM-8
Code       Company :GLENMARK
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK
Code       Company :GLENMARK C.V
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK C.V
Code       Company :GLENMARK CONSUMER CARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK CONSUMER CARE
Code       Company :GLENMARK CRITICA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK CRITICA
Code       Company :GLENMARK DERMAX
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK DERMAX
Code       Company :GLENMARK G & G
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK G & G
Code       Company :GLENMARK HEALTHEON
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK HEALTHEON
Code       Company :GLENMARK INTEGRACE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK INTEGRACE
Code       Company :GLENMARK MAJESTA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK MAJESTA
Code       Company :GLENMARK MILIEUS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK MILIEUS
Code       Company :GLENMARK RESPICARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK RESPICARE
Code       Company :GLENMARK SKINNORS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK SKINNORS
Code       Company :GLENMARK ZOLTAN
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK ZOLTAN
Code       Company :GLENMARK ZOLTAN CARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK ZOLTAN CARE
Code       Company :GLENMARK ZOLTAN MAX
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GLENMARK ZOLTAN MAX
Code       Company :GRACE WELL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GRACE WELL
Code       Company :GRACE WELL SPECIALITY
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GRACE WELL SPECIALITY
Code       Company :GRACE WELL-1
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GRACE WELL-1
Code       Company :GSK C.T.C
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GSK C.T.C
Code       Company :GSK DERMA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GSK DERMA
Code       Company :GSK FORTIOR
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GSK FORTIOR
Code       Company :GSK INGENIUM
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GSK INGENIUM
Code       Company :GSK PACC
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
GSK PACC
Code       Company :H&H COSMECEUTICAL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
H&H COSMECEUTICAL
Code       Company :H&H DERMATOLOGICAL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
H&H DERMATOLOGICAL
Code       Company :H&H HEALTHCARE
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
H&H HEALTHCARE
Code       Company :H&H VITALITY
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
H&H VITALITY
Code       Company :H&H WELLNESS
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
H&H WELLNESS
Code       Company :HEMMIPHERES PHARMA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
HEMMIPHERES PHARMA
Code       Company :HIMALAYA DENTAL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
HIMALAYA DENTAL
Code       Company :HIMALAYA ZANDRA
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
HIMALAYA ZANDRA
Code       Company :HIMALAYA ZEAL
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
HIMALAYA ZEAL
Code       Company :HIMALAYA ZENITH
Name                                           NaN
Packing                                        NaN
Name: 0, dtype: object
HIMALAYA ZENITH

In [145]:
adf = adf[1:]

In [139]:
temp = adf.to_dict(orient='records')

In [146]:
adf.to_dict(orient='records')

[{'Code': '122224R', 'Name': 'ACEPROXYVON TH 4', 'Packing': '10t'},
 {'Code': 125975, 'Name': 'ACEPROXYVON TH-8', 'Packing': '10t'},
 {'Code': 2218, 'Name': 'DECDAN VIAL', 'Packing': '2 ML'},
 {'Code': 751145, 'Name': 'ESYZA PLUS', 'Packing': '10`S'},
 {'Code': 8198, 'Name': 'HAIPD', 'Packing': '10`S'},
 {'Code': 6035, 'Name': 'INTRANIL CAPSULE', 'Packing': '6c'},
 {'Code': 2295, 'Name': 'LIBOTRYP XL 25MG', 'Packing': '10`S'},
 {'Code': 5488, 'Name': 'MERICOBAL VIVA', 'Packing': '10`S'},
 {'Code': 751036, 'Name': 'METHYCOBAL D 10', 'Packing': '10S'},
 {'Code': 2291, 'Name': 'METHYCOBAL INJ', 'Packing': '1ML'},
 {'Code': 2280, 'Name': 'METHYCOBAL TAB', 'Packing': '15S'},
 {'Code': 1735, 'Name': 'MOBIWOK PLUS', 'Packing': '10`S'},
 {'Code': 2877, 'Name': 'NORMAGUT SACHET', 'Packing': '1GM'},
 {'Code': 8114, 'Name': 'SAMMY 200 MG', 'Packing': '15`S'},
 {'Code': 8115, 'Name': 'SAMMY 400 MG', 'Packing': '10`S'},
 {'Code': 751463, 'Name': 'SPASMO PROXYVON T+', 'Packing': '25mg'},
 {'Code': 2259, 'Name': 'TRINEUROSOL -H - AMP', 'Packing': '1BOX'},
 {'Code': 2265, 'Name': 'TRYPTOMER SR', 'Packing': '15`S'}]

In [142]:
products=[]

In [20]:
adf.iloc[0].Code

1429